routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Auth::routes();
Route::group(['middleware' => 'auth'], function () {
	Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
	Route::get('/student-scores', [App\Http\Controllers\HomeController::class, 'studentScores'])
		->name('home.student-scores');
	Route::get('/grade-scores', [App\Http\Controllers\HomeController::class, 'gradeScores'])
		->name('home.grade-scores');
	Route::any('search', [App\Http\Controllers\HomeController::class, 'search'])
		->name('home.search');

	// Route::post('/filter-grade', [App\Http\Controllers\HomeController::class, ''])->name('');
	// Route::post('/filter-subject', [App\Http\Controllers\HomeController::class, ''])->name('');
	// Route::post('/filter-student', [App\Http\Controllers\HomeController::class, ''])->name('');

	Route::resources([
		'accounts' => App\Http\Controllers\AccountController::class,
		'exams'    => App\Http\Controllers\ExamController::class,
		'grades'   => App\Http\Controllers\GradeController::class,
		'scores'   => App\Http\Controllers\ScoreController::class,
		'students' => App\Http\Controllers\StudentController::class,
		'subjects' => App\Http\Controllers\SubjectController::class,
	]);

	Route::get('/teachers', [App\Http\Controllers\AccountController::class, 'indexTeachers'])
		->name('school.teachers');

	Route::post('/classroom/{grade}/promote/{to_grade?}',
		[App\Http\Controllers\ClassroomController::class, 'promote'])->name('school.classroom.promote');
	Route::post('/classroom/{grade}/graduate/',
		[App\Http\Controllers\ClassroomController::class, 'graduate'])->name('school.classroom.graduate');
	Route::get('/classroom/{grade}',
		[App\Http\Controllers\ClassroomController::class, 'scores'])->name('school.classroom.scores');

	Route::get('/import', [App\Http\Controllers\ImportController::class, 'index'])
		->name('import.index');
	Route::post('/import', [App\Http\Controllers\ImportController::class, 'import'])
		->name('import.process');


	/* for filtering scores */
	Route::prefix('search')->group(function() {
		/* by grade and years */
		/* by student and years */
		/* by subject and sudents */
	});
});

app/Http/Controllers/AccountController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use function __;
use function array_filter;
use function compact;
use function current_user;
use function redirect;
use function view;

class AccountController extends Controller {
	/**
	 * Show the form for creating a new resource.
	 *
	 * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
	 */
	public function create(Request $request) {
		if (!current_user()->is_admin()) {
			return redirect()->back()->with('toast.error', __('app.need_admin_permissions'))->send();
		}

		return view('pages.accounts.create', ['force_teacher' => $request->get('t', false)]);
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param int $id
	 *
	 * @return \Illuminate\Http\RedirectResponse
	 */
	public function destroy($id) {
		if (!current_user()->is_admin()) {
			return redirect()->back()->with('toast.error', __('app.need_admin_permissions'))->send();
		}
		$user = User::find($id);
		if (!$user) {
			return redirect()->back()->with('toast.error', 'Account not found')->send();
		}
		$name = $user->name;
		$user->delete();

		return redirect()->route('accounts.index')->with('toast.success', 'User "'.$name.'" deleted');
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param int $id
	 *
	 * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
	 */
	public function edit($id) {
		if (!current_user()->is_admin()) {
			return redirect()->back()->with('toast.error', __('app.need_admin_permissions'))->send();
		}
		$user = User::find($id);
		if (!$user) {
			return redirect()->back()->with('toast.error', 'User not found');
		}

		return view('pages.accounts.profile', compact('user'));
	}

	public function index(Request $request) {
		if (!current_user()->is_admin()) {
			return redirect()->back()->with('toast.error', __('app.need_admin_permissions'))->send();
		}
		$filter = array_filter($request->get('filter', []));
		$list = $this->_filterData($filter);

		return view('pages.accounts.index', compact('list', 'filter'));
	}

	/**
	 * Display a detail info of the resource.
	 *
	 * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
	 */
	public function show(Request $request, $id) {
		$is_owner = (current_user()->id == $id);
		if (!current_user()->is_admin() && ($is_owner)) {
			return redirect()->back()->with('toast.error', __('app.need_admin_permissions'))->send();
		}
		$user = User::find($id);
		if (!$user) {
			return redirect()->back()->with('toast.error', 'User not found');
		}

		return view('pages.accounts.profile', compact('user', 'is_owner'));
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param \Illuminate\Http\Request $request
	 *
	 * @return \Illuminate\Http\RedirectResponse
	 */
	public function store(Request $request) {
		if (!current_user()->is_admin()) {
			return redirect()->back()->with('toast.error', __('app.need_admin_permissions'))->send();
		}
		$request->validate([
			'name'     => 'required|unique:App\Models\User,name',
			'email'    => 'required|email|unique:App\Models\User,email',
			'password' => ['required', 'string', 'min:6', 'confirmed'],
		]);
		$data             = $request->all();
		$data['password'] = Hash::make($data['password']);

		$rec = new User($data);
		$rec->save();

		return redirect()->back()->with('toast.success', 'User created!');
	}

	public function indexTeachers(Request $request) {
		$filter = array_filter($request->get('filter', []));
		$list = $this->_filterData($filter, true);

		return view('pages.accounts.index', compact('list', 'filter'))->with(['title' => 'Teachers']);
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param \Illuminate\Http\Request $request
	 * @param                          $id
	 *
	 * @return \Illuminate\Http\RedirectResponse
	 */
	public function update(Request $request, $id) {
		$request->validate([
			'name'     => 'required',
			'password' => 'sometimes|string|min:8|confirmed',
			// ['required', 'string', 'min:8', 'confirmed'],
			'email'    => 'sometimes|nullable|email|unique:App\Models\User,email,'.$id,
		]);
		$data = $request->all();
		if ($request->filled('password')) {
			$data['password'] = Hash::make($data['password']);
		}
		$user = User::find($id);

		if (!current_user()->is_admin() && (current_user()->id == $id)) {
			return redirect()->back()->with('toast.error', __('app.need_admin_permissions'))->send();
		}
		if (!$user) {
			$user = new User($request->all());
			$user->save();
		} else {
			$user->update($request->all());
		}

		return redirect()->back()->with('toast.success', 'User saved!');
	}

	private function _filterData($filter, $only_teacher = false) {

		if ($only_teacher) {
			$query = User::query()->where('type', '=', 'teacher');
		} else {
			$query = User::query()->where('id', '!=', current_user()->id);
		}

		if (!empty($filter)) {
			foreach($filter as $k => $v) {
				if ($k === 'q') {
					$query->where('name', 'like', '%'.$v.'%')->orWhere('email', 'like', '%'.$v.'%');
				} else {
					$query->where($k, $v);
				}
			}
		}

		return $query->orderBy('name', 'desc')->paginate(12);
	}
}

resources/views/pages/accounts/create.blade.php
@extends('adminlte::page')

@section('title', 'LinksInspector | Add user')

@section('content')
	<section class="content-header">
		<div class="container-fluid">
			<div class="row mb-2">
				<div class="col-sm-6">
					<h1>Create {{ ($force_teacher ?? false) ? 'teacher' : 'accaunt' }}</h1>
				</div>
				<div class="col-sm-6">
					<ol class="breadcrumb float-sm-right">
						<li class="breadcrumb-item"><a href="/">Home</a></li>
						<li class="breadcrumb-item"><a href="/accounts">Accounts</a></li>
						<li class="breadcrumb-item active">New account</li>
					</ol>
				</div>
			</div>
		</div><!-- /.container-fluid -->
	</section>

	<!-- Main content -->
	<section class="content">
		<div class="container-fluid">
			<div class="row">
				<div class="col-md-12">

					<!-- Profile Image -->
					<div class="card card-primary card-outline">
						<div class="card-body box-profile">
							<form class="form-horizontal" method="POST" action="{{ route('accounts.store') }}">
								@csrf
								@method('POST')
								<div class="form-group row">
									<label for="inputName" class="col-sm-2 col-form-label">Name</label>
									<div class="col-sm-10">
										<input type="text" class="form-control @error('name') is-invalid @enderror"
											id="inputName" name="name" value="{{ old('name') }}"
											placeholder="Name">

										@error('name')
										<span class="invalid-feedback" role="alert">
											<strong>{{ $message }}</strong>
										</span>
										@enderror
									</div>
								</div>

								<div class="form-group row">
									<label for="inputEmail" class="col-sm-2 col-form-label">Email</label>
									<div class="col-sm-10">
										<input type="email" class="form-control @error('email') is-invalid @enderror"
											id="inputEmail" name="email" value="{{ old('email') }}"
											placeholder="Email">

										@error('email')
										<span class="invalid-feedback" role="alert">
											<strong>{{ $message }}</strong>
										</span>
										@enderror
									</div>
								</div>
								{{-- Password field --}}
								<div class="form-group row">
									<label for="inputPass" class="col-sm-2 col-form-label">Password</label>
									<div class="col-sm-10">
										<div class="input-group">
											<input type="password"
												class="form-control @error('password') is-invalid @enderror"
												name="password" id="inputPass" value="{{ old('password') }}"
												placeholder="{{ __('adminlte::adminlte.password') }}"
												data-toggle="password">
											<div class="input-group-append">
												<div class="input-group-text password-show-toggle"
													title="Show / hide password">
													<span class="fas fa-eye"></span>
												</div>
											</div>

											@error('password')
											<span class="invalid-feedback" role="alert">
												<strong>{{ $message }}</strong>
											</span>
											@enderror
										</div>

									</div>
								</div>


								{{-- Confirm password field --}}
								<div class="form-group row">
									<label for="inputPass" class="col-sm-2 col-form-label">&nbsp;</label>
									<div class="col-sm-10">
										<div class="input-group">
											<input type="password" name="password_confirmation"
												class="form-control @error('password_confirmation') is-invalid @enderror"
												data-toggle="password"
												placeholder="{{ __('adminlte::adminlte.retype_password') }}">

											<div class="input-group-append">
												<div class="input-group-text password-show-toggle"
													title="Show / hide password">
													<span class="fas fa-eye"></span>
												</div>
											</div>
											@error('password_confirmation')
											<span class="invalid-feedback" role="alert">
												<strong>{{ $message }}</strong>
											</span>
											@enderror
										</div>


									</div>
								</div>
								<input type="hidden" name="type" value="teacher">
								<div class="form-group row {{ ($force_teacher ?? false) ? 'hidden' : '' }}">
									<div class="offset-sm-2 col-sm-10">
										<div class="checkbox">
											<label><input type="checkbox" name="type" value="admin"
													{{ old('type') === 'admin' ? 'checked' : '' }}>&nbsp;<b class="text-red">Is admin</b> account</label>
										</div>
									</div>
								</div>
								<div class="form-group row">
									<div class="offset-sm-2 col-sm-10">
										<button type="submit" class="btn btn-flat btn-primary">Save account</button>
									</div>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
@stop

resources/views/pages/accounts/index.blade.php
@extends('adminlte::page')

@section('title', ' | '.($title ?? 'Accounts'))

@section('content')
	<!-- Main content -->
	<section class="content">

		<!-- Default box -->
		<div class="card card-warning card-outline">
			<div class="card-header d-flex">
				<h3 class="card-title p-1">
					<i class="fas fa-list-alt"></i> {{ ($title ?? 'Accounts') }}
				</h3>
				<ul class="nav nav-pills ml-auto">
					<li class="nav-item">
						<span class="nav-link">Search by name or email:</span>
					</li>
					<li class="nav-item" style="width: 240px;">
						<form method="get">
							<input type="search" class="form-control search-title form-control-sm nav-link" name="filter[q]" placeholder="Search by name or email" value="{{ $filter['q'] ?? '' }}">
						</form>
					</li>
				</ul>
			</div>
			<div class="card-body pb-0">
				@if(current_user()->is_admin())
					<a href="{{ isset($title) ? route('accounts.create', ['t'=>1]) : route('accounts.create') }}" class="btn btn-primary mb-3">+ create new</a>
				@endif
				@if ($list->links())
					<div class="float-right">
						{{ $list->links() }}
					</div>
				@endif
				<div class="row">
					@if (count($list))
						@foreach($list as $user)
							<div class="col-12 col-sm-4 col-md-3 d-flex align-items-stretch flex-column">
								<div class="card bg-light d-flex flex-fill">
									<div class="card-header text-muted border-bottom-0"
										style="padding-left: 1rem;padding-right: 1rem;">
										<span class="">
											@if($user->is_admin())
                                                <b class="text-danger">administrator</b>
											@else
												<span class="text-primary">teacher</span>
											@endif
										</span>
									</div>
									<div class="card-body pt-0" style="padding: 1rem;">
										<div class="row">
											<div class="col-7">
												<h2 class="lead"><b>{{ $user->name }}</b></h2>

												<ul class="ml-3 mb-0 fa-ul text-muted" style="font-size: 15px;">
													@if($user->email)
														<li class="small mb-1">
															<a href="mailto:{{$user->email}}" title="Send mail">
																<span class="fa-li"><i class="fas fa-envelope"></i>
																</span>
															</a>
															{{ $user->email }}
														</li>
													@endif
												</ul>
											</div>
											<div class="col-5 text-center">
												<img src="{{$user->adminlte_image()}}"
													alt="{{$user->name}} avatar" class="img-circle img-fluid">
											</div>
										</div>
									</div>
									<div class="card-footer">
										<div class="text-right">
											@if(current_user()->is_admin())
												<a href="{{route('accounts.show', ['account' => $user->id])}}" class="btn btn-sm btn-primary btn-flat mr-1">
													<i class="fas fa-user"></i> View profile
												</a>
												<form
													action="{{ route('accounts.destroy', ['account' => $user->id]) }}"
													method="post" class="float-right">
													@csrf
													@method('DELETE')
													<button type="submit" class="btn btn-sm btn-flat btn-danger"
														onclick="return confirm('Confirm delete account?')">
														<i class="fas fa-trash-alt"></i>
													</button>
												</form>
											@endif
										</div>
									</div>
								</div>
							</div>
						@endforeach
					@endif
				</div>
			</div>
			<!-- /.card-body -->
			<div class="card-footer">
				@if ($list->links())
					<h4 class="float-left">Showing {{$list->firstItem()}} to {{$list->lastItem()}} of {{$list->total()}} entries
					</h4>
					<div class="float-right">
						{{ $list->links() }}
					</div>
				@endif
			</div>
			<!-- /.card-footer -->
		</div>
		<!-- /.card -->

	</section>
@stop

resources/views/pages/accounts/profile.blade.php
@extends('adminlte::page')

@section('title', ' | Profile info')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Profile</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="route('accounts.index')">Accounts</a></li>
                        <li class="breadcrumb-item active">Profile</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-3">

                    <!-- Profile Image -->
                    <div class="card card-primary card-outline">
                        <div class="card-body box-profile">
                            <div class="text-center">
                                <img class="profile-user-img img-fluid img-circle"
                                    src="{{ $user->adminlte_image() }}"
                                    alt="User profile picture">
                            </div>

                            <h3 class="profile-username text-center">{{ $user->name }}</h3>

                            <p class="text-muted text-center">
                                @if($user->is_admin())
                                   administrator
                                @else
                                   teacher
                                @endif
                            </p>

                            <ul class="list-group list-group-unbordered mb-3">
                                <li class="list-group-item">
                                    <b>Email: </b> <a class="float-right" 
                                    href="mailto:{{$user->email}}">
                                        {{$user->email}}
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <!-- /.card-body -->
                    </div>
                </div>
                <!-- /.col -->
                <div class="col-md-9">
                    <div class="card">
                        <div class="card-body">
                            <form class="form-horizontal" method="POST" action="{{ route('accounts.update', ['account'=>$user->id]) }}">
                                @csrf
                                @method('PUT')
                                <div class="form-group row">
                                    <label for="inputName" class="col-sm-2 col-form-label">Name</label>
                                    <div class="col-sm-10">
                                        <input type="text" class="form-control @error('name') is-invalid @enderror"
                                            id="inputName" name="name" value="{{ old('name', $user->name) }}"
                                            placeholder="Name">

                                        @error('name')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="inputEmail" class="col-sm-2 col-form-label">Email</label>
                                    <div class="col-sm-10">
                                        <input type="email" class="form-control @error('email') is-invalid @enderror"
                                            id="inputEmail" name="email" value="{{ old('email', $user->email) }}"
                                            placeholder="Email">

                                        @error('email')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <div class="offset-sm-2 col-sm-10">
                                        <hr>
                                    </div>
                                </div>



                                <div class="form-group row">
                                    <div class="offset-sm-2 col-sm-10">
                                        <hr>
                                    </div>
                                </div>
                                <input type="hidden" name="type" value="{{$user->type}}">

                                @if(current_user()->is_admin())
                                    <div class="form-group row">
                                        <div class="offset-sm-2 col-sm-10">
                                            <div class="checkbox">
                                                <label><input type="checkbox" name="type" value="admin"
                                                        {{ old('type', $user->type) === 'admin' ? 'checked' : '' }}>&nbsp;<b class="text-red">Is admin</b> account</label>
                                            </div>
                                        </div>
                                    </div>
                                @endif

                                <div class="form-group row">
                                    <div class="offset-sm-2 col-sm-10">
                                        <button type="submit" class="btn btn-flat btn-primary">
                                            Save settings</button>
                                    </div>
                                </div>
                            </form>
                            <!-- /.tab-content -->
                        </div><!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
@stop