routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Auth::routes();
Route::group(['middleware' => 'auth'], function () {
	Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
	Route::get('/student-scores', [App\Http\Controllers\HomeController::class, 'studentScores'])
		->name('home.student-scores');
	Route::get('/grade-scores', [App\Http\Controllers\HomeController::class, 'gradeScores'])
		->name('home.grade-scores');
	Route::any('search', [App\Http\Controllers\HomeController::class, 'search'])
		->name('home.search');

	// Route::post('/filter-grade', [App\Http\Controllers\HomeController::class, ''])->name('');
	// Route::post('/filter-subject', [App\Http\Controllers\HomeController::class, ''])->name('');
	// Route::post('/filter-student', [App\Http\Controllers\HomeController::class, ''])->name('');

	Route::resources([
		'accounts' => App\Http\Controllers\AccountController::class,
		'exams'    => App\Http\Controllers\ExamController::class,
		'grades'   => App\Http\Controllers\GradeController::class,
		'scores'   => App\Http\Controllers\ScoreController::class,
		'students' => App\Http\Controllers\StudentController::class,
		'subjects' => App\Http\Controllers\SubjectController::class,
	]);

	Route::get('/teachers', [App\Http\Controllers\AccountController::class, 'indexTeachers'])
		->name('school.teachers');

	Route::post('/classroom/{grade}/promote/{to_grade?}',
		[App\Http\Controllers\ClassroomController::class, 'promote'])->name('school.classroom.promote');
	Route::post('/classroom/{grade}/graduate/',
		[App\Http\Controllers\ClassroomController::class, 'graduate'])->name('school.classroom.graduate');
	Route::get('/classroom/{grade}',
		[App\Http\Controllers\ClassroomController::class, 'scores'])->name('school.classroom.scores');

	Route::get('/import', [App\Http\Controllers\ImportController::class, 'index'])
		->name('import.index');
	Route::post('/import', [App\Http\Controllers\ImportController::class, 'import'])
		->name('import.process');


	/* for filtering scores */
	Route::prefix('search')->group(function() {
		/* by grade and years */
		/* by student and years */
		/* by subject and sudents */
	});
});

app/Models/Student.php
<?php

namespace App\Models;

use App\Casts\Json;
use App\Models\Traits\HasUser;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use RKD\PersonalIdCode\PersonalIdCode;
use function current_user;
use function now;
use function time;

/**
 * App\Models\Student
 *
 * @property int         $id
 * @property string      $first_name
 * @property string      $last_name
 * @property string|null $birth_year
 * @property int         $grade_id
 * @property string|null $isikukood
 * @property string                                                            $lang
 * @property int|null                                                          $user_id
 * @property mixed|null                                                        $_data
 * @property \Illuminate\Support\Carbon|null                                   $created_at
 * @property \Illuminate\Support\Carbon|null                                   $updated_at
 * @property string|null                                                       $deleted_at
 * @property-read \App\Models\Grade                                            $grade
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Score[] $scores
 * @property-read int|null                                                     $scores_count
 * @property-read \App\Models\User|null                                        $user
 * @method static \Illuminate\Database\Eloquent\Builder|Student newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Student newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Student query()
 * @method static \Illuminate\Database\Eloquent\Builder|Student whereBirthYear($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Student whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Student whereData($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Student whereDeletedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Student whereFirstName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Student whereGradeId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Student whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Student whereIsikukood($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Student whereLang($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Student whereLastName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Student whereUpdatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Student whereUserId($value)
 * @mixin \Eloquent
 * @property int                                                               $status 0 - not active; 1 - active; 2 -
 *           alumnus;
 * @property string|null                                                       $description
 * @property-read mixed                                                        $full_name
 * @method static \Illuminate\Database\Eloquent\Builder|Student whereDescription($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Student whereStatus($value)
 */
class Student extends Model {
	use HasFactory, HasUser;

	const LANG_LABELS = [
		'est' => 'Estonian',
		'rus' => 'Russian',
	];

	protected $casts   = [
		'updated_at' => 'datetime:d.m.Y H:i:s',
		'_data'      => Json::class,
	];
	protected $dates   = ['updated_at', 'created_at'];
	protected $guarded = ['id'];
	protected $table   = 'students';
	/**
	 * @var \App\Models\PersonalIdCode
	 */
	private $personalCode;

	public static function getOrCreate($full_name, $isikukood, $lang = 'est', $grade_id = null, $status = 1) {
		if (empty($full_name) || empty($isikukood)) {
			return null;
		}

		[$first_name, $last_name] = explode(' ', $full_name, 2);

		$student = self::where('isikukood', $isikukood)->first();

		if ($student) {
			$student->update([
				'first_name' => $first_name,
				'last_name'  => $last_name,
			]);

			return $student;
		}

		$student = static::firstOrCreate([
			'first_name' => $first_name,
			'last_name'  => $last_name,
			'isikukood'  => $isikukood
		], [
			'grade_id'   => $grade_id ?? Grade::firstWhere('id', '>', 0)->id,
			'lang'       => $lang ?? 'est',
			'status'     => $status,
			'user_id'    => current_user()->id,
			'created_at' => now(),
		]);

		return $student;
	}

	protected static function booted() {
		static::creating(function($record) {
			$record->user_id = current_user()->id;
		});

		static::updating(function(Model $record) {
			if ($record->isDirty('grade_id')) {
				$data                      = $record->_data ?? ['transfers' => []];
				$data['transfers'][time()] = [
					'from' => $record->getOriginal('grade_id', '-'),
					'to'   => $record->grade_id,
				];

				$record->_data = $data;
			}
		});
	}

	public static function validateIsikukood($code) {
		return (new PersonalIdCode($code))->validate();
	}

	public function exams() {
		$grade_level = $this->grade->level;

		return Exam::where('grade_level', $grade_level)->get();
	}

	public function getAgeAttribute() {
		return $this->getPersonalCode()->getAge();
	}

	public function getLanguageAttribute() {
		return self::LANG_LABELS[$this->lang] ?? $this->lang;
	}

	public function getCurrGradeAttribute() {
		return $this->grade->name;
	}

	public function getBirthDateAttribute() {
		return $this->getPersonalCode()->getBirthDate()->format('d.m.Y');
	}

	public function getFullNameAttribute() {
		return trim($this->first_name.' '.$this->last_name);
	}

	/**
	 * Get personalCode
	 *
	 * @return \RKD\PersonalIdCode\PersonalIdCode
	 */
	public function getPersonalCode():PersonalIdCode {
		if (!$this->personalCode) {
			$this->personalCode = new PersonalIdCode($this->isikukood);
		}

		return $this->personalCode;
	}

	/**
	 * Scope a query to only include active students.
	 *
	 * @param \Illuminate\Database\Eloquent\Builder $query
	 *
	 * @return void
	 */
	public function scopeActive($query) {
		$query->where('status', 1);
	}

	/**
	 * Scope a query to only include active users.
	 *
	 * @param \Illuminate\Database\Eloquent\Builder $query
	 *
	 * @return void
	 */
	public function scopeGraduated($query) {
		$query->where('status', 2)->orWhereNotNull('graduated_at');
	}

	public function grade() {
		return $this->belongsTo(Grade::class);
	}

	public function image() {
		return '/img/default-student.png';
	}

	public function scores() {
		return $this->hasMany(Score::class)->orderBy('subject_id');
	}
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;
use App\Models\Exam;
use App\Models\Grade;
use App\Models\Score;
use App\Models\Student;
use App\Models\Subject;
use App\Services\ScoreFinder;
use DB;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
use Illuminate\View\View;
use function back;
use function compact;
use function count;
use function implode;
use function in_array;
use function is_numeric;
use function view;

class HomeController extends Controller {

	/**
	 * Show search results.
	 *
	 * @param Request $request
	 *
	 * @return View
	 */
	public function search(Request $request) {
		if (!$request->filled('q')) {
			return back();
		}
		// Get the search keyword.

		$q = $request->input('q');

		Log::info("Search next keyword: `{$q}`");
		$students = Student::where(DB::raw('lower(first_name)'), 'like', '%'.mb_strtolower($q ?? '').'%')
			->orWhere(DB::raw('lower(last_name)'), 'like', '%'.mb_strtolower($q ?? '').'%')
			->orWhere('isikukood', 'like', '%'.mb_strtolower($q ?? '').'%')->get();
		return view('pages.home.search-result', compact('q', 'students'));
		// ['q' => $q, 'results' => $students]);
	}

	public function index(Request $request) {
		$students = Student::orderBy('grade_id')->orderBy('first_name')->get();
		$subjects = Subject::orderBy('name')->get();
		$exams    = Exam::orderBy('grade_level')->get();
		$grades   = Grade::withCount('students')->orderBy('level')->get();
		$stats    = [
			'students' => $students->count(),
			'subjects' => $subjects->count(),
			'grades'   => $grades->count(),
			'exams'    => $exams->count(),
		];

		return view('pages.home.index', compact('stats', 'students', 'grades', 'subjects'));
	}

	public function gradeScores(Request $request) {
		$grades     = Grade::find($request->grade_id);
		$offset = Grade::LEVEL_MAX; /* MAX period */
		if (!is_numeric($request->term)) {
			$offset = $grades[0]->level; /* as period */
			$term_label    = 'All time';
		} else {
			$offset_period = $request->term; /* as period */
			$term_label    = ($offset_period > 0) ? 'Last '.($request->term + 1).' years' : 'Last year';
		}
		$exam_type  = $request->exam_type;
		$type_label = in_array($exam_type, [Exam::TYPE_SCHOOL, Exam::TYPE_GOVERNMENT], true)
			? $exam_type.' only'
			: implode(' & ', [Exam::TYPE_SCHOOL, Exam::TYPE_GOVERNMENT]);
		$subject    = Subject::find($request->subject_id);

		$all_exams    = Exam::get()->keyBy(['id'])->all();
		$all_subjects = Subject::get()->keyBy(['id'])->all();
		$all_grades   = Grade::get()->keyBy(['id'])->all();
		$all_students = Student::get()->keyBy(['id'])->all();

		$dataset = [];
		foreach($grades as $grade) {
			$dataset[$grade->name] = ScoreFinder::gradeScores($grade->id, [
				'subject_id' => $subject['id'] ?? null,
				'exam_type'  => $exam_type,
			], $offset); /* [grade_id](0..N)->[student_id][exam_id] */
		}

		return $subject 
			? view('pages.home.parts._grade_subject_scores',
				compact('dataset', 
					'all_students', 'all_exams', 'all_grades', 'all_subjects',
					'term_label', 'type_label', 'subject'))
			: view('pages.home.parts._grade_scores',
				compact('dataset', 
					'all_students', 'all_exams', 'all_grades', 'all_subjects',
					'term_label', 'type_label', 'subject'));
	}

	public function studentScores(Request $request) {
		$student       = Student::find($request->student_id);
		$offset_period = Grade::LEVEL_MAX; /* MAX period */
		if (!is_numeric($request->term)) {
			$offset_period = $student->grade->level; /* as period */
			$term_label    = 'All time';
		} else {
			$offset_period = $request->term; /* as period */
			$term_label    = ($offset_period > 0) ? 'Last '.($request->term + 1).' years' : 'Last year';
		}
		$offset_years = $request->terms; /* as years */

		$curr_grade_id = $student->grade_id;
		$exam_type     = $request->exam_type;

		$type_label = in_array($exam_type, [Exam::TYPE_SCHOOL, Exam::TYPE_GOVERNMENT], true)
			? $exam_type.' only'
			: implode(' & ', [Exam::TYPE_SCHOOL, Exam::TYPE_GOVERNMENT]);

		$subject = [];
		if ($request->subject_id > 0) {
			$subject = Subject::find($request->subject_id);
		}
		$f__get_result = function($i) use ($student, $curr_grade_id, $exam_type, $request) {
			if ($i == 0) {
				$grade = $student->grade;
			} else {
				$grade = Grade::getGradeByOffset($curr_grade_id, $i * -1);
			}
			if (!$grade){
				return false;
			}
			if (in_array($exam_type, [Exam::TYPE_SCHOOL, Exam::TYPE_GOVERNMENT], true)) {
				$qry = Score::whereHas('exam', function(Builder $query) use ($exam_type) {
					$query->where('type', $exam_type);
				})->where('student_id', $student->id)->where('grade_id', $grade->id);
			} else {
				$qry = Score::where('student_id', $student->id)->where('grade_id', $grade->id);
			}

			if ($request->subject_id > 0) {
				$qry = $qry->whereHas('exam', function(Builder $query) use ($request) {
					$query->where('subject_id', $request->subject_id);
				});
			}

			return ['grade_name' => $grade->name, 'scores' => $qry->orderBy('exam_id')->with('exam')->get()];
		};

		$scores = [];
		if ($request->term_type === 'years') {
			foreach($offset_years as $i) {
				$res = $f__get_result($i);
				if ($res && count($res['scores'])) {
					$scores[$res['grade_name']] = $res['scores'] ?? [];
				}
			}
		} else {
			for($i = 0; $i <= $offset_period; $i++) {
				$res = $f__get_result($i);
				if ($res && count($res['scores'])) {
					$scores[$res['grade_name']] = $res['scores'] ?? [];
				}
			}
		}

		return view('pages.home.parts._student_scores',
			compact('scores', 'student', 'subject', 'term_label', 'type_label', 'offset_period')
		);
	}


}

resources/views/pages/students/create.blade.php
@extends('adminlte::page')

@section('title', ' | Add student')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Create user</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="/">Students</a></li>
                        <li class="breadcrumb-item active">New user</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">

                    <!-- Profile Image -->
                    <div class="card card-primary card-outline">
                        <div class="card-body box-profile">
                            <form class="form-horizontal" method="POST" action="{{ route('students.store') }}">
                                @csrf
                                @method('POST')
                                <div class="form-group row">
                                    <div class="input-group col-md-6">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text">
                                                First name <code class="text-danger ml-1">*</code>
                                            </span>
                                        </div>
                                        <input class="form-control @error('first_name') is-invalid @enderror"
                                            type="text" id="first_name" name="first_name"
                                            minlength="2"
                                            value="{{ old('first_name') }}"
                                            placeholder="First name" required>
                                        @error('first_name')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                    <div class="input-group col-md-6">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text">
                                                Last name <code class="text-danger ml-1">*</code>
                                            </span>
                                        </div>
                                        <input class="form-control @error('last_name') is-invalid @enderror"
                                            type="text" id="last_name" name="last_name"
                                            minlength="2"
                                            value="{{ old('last_name') }}"
                                            placeholder="Last name" required>
                                        @error('last_name')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="isikukood" class="col-sm-2 col-form-label">Isikukood
                                        <code class="text-danger ml-1">*</code></label>
                                    <div class="col-sm-6">
                                        <input class="form-control @error('isikukood') is-invalid @enderror"
                                            type="text" name="isikukood" id="isikukood-value"
                                            value="{{ old('isikukood') }}" minlength="11"
                                            pattern="[\d\+\s]*" required
                                            placeholder="Isikukood code (11 digits)">

                                        @error('isikukood')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                    <div class="col-sm-6" id="isikukood-validate">
                                        
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="lang" class="col-sm-2 col-form-label">Mother tongue:</label>
                                    <div class="col-sm-10">
                                        <select required name="lang" id="lang"
                                            class="custom-select @error('lang') is-invalid @enderror">
                                            <option>- select lang. -</option>
                                            <option value="rus" @if(old('lang') == 'rus') selected @endif>
                                                Russian
                                            </option>
                                            <option value="est" @if(old('lang') == 'est') selected @endif>
                                                Estonian
                                            </option>
                                        </select>
                                        @error('lang')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="grade_id" class="col-sm-2 col-form-label">Current grade</label>
                                    <div class="col-sm-10">
                                        <select required name="grade_id" id="grade_id"
                                            class="select2 @error('grade_id') is-invalid @enderror"
                                        >
                                            <option>- select grade -</option>
                                            @foreach($grades as $grade)
                                                <option value="{{ $grade->id }}"
                                                    data-level="{{ $grade->level }}"
                                                    data-adv="{{$grade->students_count}} students">
                                                    {{ $grade->name }}
                                                </option>
                                            @endforeach
                                        </select>

                                        @error('grade_id')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                </div>

                                <div class="form-group">
                                    <hr>
                                </div>
                                <div class="form-group">
                                    <label for="description">Description</label>
                                    <textarea name="description" {{($readonly ?? false) ? 'readonly' : ''}} class="form-control @error('description') is-invalid @enderror" id="description" rows="4">{{ old('description') }}</textarea>
                                    @error('description')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                                <div class="form-group row">
                                    <div class="offset-sm-7 col-sm-3">
                                        <button type="submit" class="btn btn-primary btn-block">Save</button>
                                    </div>
                                    <div class="col-sm-2">
                                        <a href="{{ route('students.index') }}"
                                            class="btn btn-default btn-block">Back</a>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
@endsection

@section('css')
    <style>
		#filters .custom-select-sm,
		#filters, .select2-results {
			font-size : 12px !important;
		}
		label .label-descr {
			letter-spacing : -0.3px;
		}
		textarea#domain-list {
			resize : none;
		}
		#isikukood-validate span {
            line-height: 2.6em;
		}
    </style>
@endsection
@section('plugins.Select2', true)
@push('js')
    <script src="{{asset('vendor/isikukood.min.js')}}"></script>
    <script>
		$(function () {
            $('#isikukood-value').on('input', function(e){
                var _result_wrapper = $('#isikukood-validate');
                _result_wrapper.hide();
            });
            $('#isikukood-value').on('change', function(e){
                var _result_wrapper = $('#isikukood-validate');
                var _ik_code = $(this).val();
                _result_wrapper.show();
                if (_ik_code.length < 11){
                    _result_wrapper.html('<span class="text-warning"><i class="fas fa-exclamation-triangle"></i> Isikukood not valid. </span>');
                    return;
                } 
                var ik = new Isikukood(_ik_code);
                var is_valid = ik.validate();
                if (!is_valid){
                    _result_wrapper.html('<span class="text-warning"><i class="fas fa-exclamation-triangle"></i> Isikukood not valid. </span>');
                    return;
                }
                _result_wrapper.html('<span class="text-success"><i class="fas fa-check"></i>&emsp;' +
                    '<b>Birthday: '+ik.getBirthday().toLocaleDateString()+'; Gender: '+ik.getGender()+'</b></span>');
            });
			$('.select2').select2({
				theme: "bootstrap4",
				width: "style",
				placeholder: '- any -',
				allowClear: true,
				escapeMarkup: function (markup) {
					return markup;
				},
				templateResult: function (data) {
					var _custom = $(data.element).data('adv');
					if (!!_custom) {
						return $('<span>' + data.text + '</span><b style="float:right">' + _custom + '</b>');
					}
					return data.text;
				},
				templateSelection: function (data) {
					var _custom = $(data.element).data('adv');
					if (!!_custom) {
						return $('<span>' + data.text + '</span><b style="float:right">' + _custom + '</b>');
					}
					return data.text;
				}
			});
			bsCustomFileInput.init();
		});
    </script>
@endpush

resources/views/pages/students/view.blade.php
@extends('adminlte::page')

@section('title', 'Student profile')

@section('content')
	<section class="content-header">
		<div class="container-fluid">
			<div class="row mb-2">
				<div class="col-sm-6">
					<h1>Student Profile</h1>
				</div>
				<div class="col-sm-6">
					<ol class="breadcrumb float-sm-right">
						<li class="breadcrumb-item"><a href="/">Home</a></li>
						<li class="breadcrumb-item"><a href="{{ route('students.index') }}">Students</a></li>
						<li class="breadcrumb-item active">Profile</li>
					</ol>
				</div>
			</div>
		</div><!-- /.container-fluid -->
	</section>

	<!-- Main content -->
	<section class="content">
		<div class="container-fluid">
			<div class="row">
				<div class="col-md-3">
					<!-- Profile  -->
					<div class="card card-primary card-outline">
						<div class="card-body box-profile">
							<div class="text-center">
								<img class="profile-user-img img-fluid img-circle"
									src="{{ $rec->image() }}"
									alt="User profile picture">
							</div>

							<h2 class="profile-username text-center">
								{{ $rec->full_name }}<br>
								<small style="font-size: 14px; color:#777;" title="Current grade">
									{{ $rec->grade->name }}
								</small>
							</h2>

							<ul class="list-group list-group-unbordered mb-3">
								<li class="list-group-item">
									<b>Isikukood: </b>
									<span class="text-primary float-right">{{ $rec->isikukood }}</span>
								</li>
								@if($rec->getPersonalCode()->validate())
									<li class="list-group-item">
										<b>Birth Date: </b>
										<span class="text-primary float-right">{{ $rec->birth_date }}</span><br>
										<small class="mt-1 text-dark float-right">{{ $rec->age }} years old</small>
									</li>
								@endif
								<li class="list-group-item">
									<b>Lang: </b>
									<span class="text-primary float-right">{{ ucfirst($rec->language) }}</span>
								</li>
								@if($rec->description)
									<li class="list-group-item border-0">
										<b class="mb-2">Description: </b>
										<p class="text-gray-dark m-0 mt-2 p-2 bg-light"
											style="min-height:4em; max-height: 8em; overflow-y: auto;">{!! nl2br($rec->description)  !!}</p>
									</li>
								@endif
							</ul>
							@if(current_user()->is_admin())
								<a href="{{ route('students.edit', ['student'=>$rec->id]) }}"
									class="btn btn-primary btn-block"><b>Edit</b></a>
							@endif
						</div>
						<!-- /.card-body -->
					</div>
				</div>
				<!-- /.col -->
				<div class="col-md-9">
					<div class="card">

						<div class="card-body">
						@include('pages.students.parts.scores-timeline', ['rec' => $rec, 'scores' => $scores])
						<!-- /.tab-content -->
						</div><!-- /.card-body -->
					</div>
					<!-- /.card -->
				</div>
				<!-- /.col -->
			</div>
			<!-- /.row -->
		</div><!-- /.container-fluid -->
	</section>
	<!-- /.content -->
@stop